""" Cryptography
Module generation for tokenizing passwords as password hashes. """

from cryptography.fernet import Fernet
import base64

# generate a key for encryption and decryption
# You can use fernet to generate
# the key or use random key generator
# here I'm using fernet to generate key
 
# Static key generated using Fernet.generate_key(), not applicable for production purposes.
_key = b'k4hpuVzgUjBleIOCnnoZ3kkCI7xFPPBfL4NdFTgCbs4='

class Security(Fernet):

    def __init__(self) -> None:
        super().__init__(_key)

    def EncryptData(self, text:str) -> str:
        """ Takes a string as a parameter to return a base64 decoded, string type, key generated by Fernet and the text as a decoded"""
        return base64.b64encode(self.encrypt(text.encode())).decode()
    
    def DecryptData(self, hashStr: str) -> str:
        """ Returns a string decryption of the hash: string type arg """
        return self.decrypt(base64.b64decode(hashStr).decode()).decode()
